spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.ys.cms.model

      