spring:
  application:
    name: microservice-cms-log
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    #hostname: ${spring.cloud.client.ip-address}
    #lease-renewal-interval-in-seconds: 10 # 每隔10s发送一次心跳
    #lease-expiration-duration-in-seconds: 30 # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
  client:
    register-with-eureka: true #是否向服务注册中心注册自己
    fetch-registry: true #是否检索服务  
    #healthcheck:
      #enable: true   
    service-url:
      defaultZone: http://admin:pass1234@localhost:8761/eureka/     
      